### ISSUE TITLE
DMG recommendations

### ISSUE THREAD

**Issue by pornel** [sparkle-project/sparkle-project.github.io#39]
> Avoid placing your app inside another folder in your archive. If you ship an archive that is not a dmg on your product’s website, which we do not recommend, the archive should then not contain multiple items. An exception to this guideline is if you use a signed dmg, but please be careful - the system may not warn you if the dmg is not signed properly!

I don't understand what DMG signing has to do with folders. This paragraph is complicated.

Apart from that:

* App translocation applies to unsigned DMG and ZIP/tarballs, so we don't recommend those for product's website.
* DMG is slow and hacky in Sparkle, so we shouldn't recommend it for update archives.

Should we change recommendation to:

* Use signed DMG on the website.
* Use tarball for Sparkle. 
* Use tarballs for everthing if you can't sign the DMG?

**Comment by zorgiepoo** [comment]
> I don't understand what DMG signing has to do with folders. This paragraph is complicated.

Generally you don't want your archive to be expanded by creating another folder, especially if you don't sign the archive. For zip, this means that there shouldn't be multiple items in the archive. For dmg, this means you shouldn't create intermediate folders containing your app (but if you sign the dmg, you're okay).

> App translocation applies to unsigned DMG and ZIP/tarballs, so we don't recommend those for product's website.

Agreed. Like I said above, if you can't afford to code sign, you can still try to distribute your archive in a way that increases your chances of avoiding translocation.

> DMG is slow and hacky in Sparkle, so we shouldn't recommend it for update archives.

Agreed.

> Use tarballs for everthing if you can't sign the DMG?

I think we may want to stay out that recommendation. Also zip vs tarball doesn't mean a whole lot of difference to me, not sure if you're lumping those together.

**Comment by pornel** [comment]
> Generally you don't want your archive to be expanded by creating another folder, especially if you don't sign the archive.

Why? How does signing change things?

**Comment by zorgiepoo** [comment]
So you know how if the user moves the app elsewhere using Finder, the app is not translocated anymore? That does not apply in the case if the user moves a folder that contains the app; in that case, the app is still translocated.

If you create a zip or tar with multiple items, after extraction, an intermediate folder containing the app will exist. Not necessarily so for dmg, unless you explicitly create a folder inside the dmg and shove app(s) in that intermediate folder.

If the dmg is signed, none of the above matters, since the act of signing the dmg already opted the app out of translocation.
